name: build-playground/CopyPublishBuildArtifactsTest
on:
  workflow_dispatch:
env:
  SYSTEM.DEBUG: 'false'
jobs:
  Job_2:
    name: Copy Publish Build artifacts Job
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: dotnet build
      run: 'dotnet build Sox_Audito_ACL_Poc/Sox_Audito_ACL_Poc.sln --configuration Release '
    # The following script preserves the globbing behavior of the CopyFiles task.
    - name: 'Copy Publish Artifact: Sox_Audito_ACL_Poc'
      uses: actions/github-script@v3
      env:
        TARGET_FOLDER: "${{ runner.temp }}/${{ github.run_id }}_publishartifact"
        SOURCE_FOLDER: Sox_Audito_ACL_Poc
        CONTENTS: "**\\bin\\Release"
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        script: |-
          const fs = require('fs').promises
          const path = require('path')
          const target = path.resolve(process.env.TARGET_FOLDER)
          process.chdir(process.env.SOURCE_FOLDER || '.')
          if (process.env.CLEAN_TARGET_FOLDER === 'true') await io.rmRF(target)
          const flattenFolders = process.env.FLATTEN_FOLDERS === 'true'
          const options = {force: process.env.OVERWRITE === 'true'}
          const globber = await glob.create(process.env.CONTENTS || '**')
          for await (const file of globber.globGenerator()) {
            if ((await fs.lstat(file)).isDirectory()) continue
            const filename = flattenFolders ? path.basename(file) : file.substring(process.cwd().length)
            const dest = path.join(target, filename)
            await io.mkdirP(path.dirname(dest))
            await io.cp(file, dest, options)
          }
    - name: 'Copy Publish Artifact: Sox_Audito_ACL_Poc'
      uses: actions/upload-artifact@v2
      with:
        name: Sox_Audito_ACL_Poc
        path: "${{ runner.temp }}/${{ github.run_id }}_publishartifact"
