name: Evaluator

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    steps:
     - name: Executing VSTest
       continue-on-error: true
       env:
        DEFAULT_ROOT: ${{github.workspace}}
        RESULTS_FOLDER: ${{ runner.temp }}/${{ github.run_id }}_resultsfolder
        SEARCH_PATTERN: "**\\*UnitTest*.dll;!**\\*TestAdapter.dll;!**\\obj\\**;!**\\ref\\**"
        ARGS: "/Platform:x64; /ResultsDirectory:${{ runner.temp }}/${{ github.run_id }}_resultsfolder;/Logger:trx"
       shell: pwsh
       run: |
         Write-Host "hello"
    
