# This is a basic workflow to help you get started with Actions

name: extract0-files-validation

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows_validation_job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract Files
        run: 7z x **/*.zip -obase_folder -aoa

          

