# This is a basic workflow to help you get started with Actions

name: extract-files-validation

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows_validation_job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract Files
        run: 7z x ./test/*.zip -obase_folder -aoa
        
  ubuntu_validation_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract Files
        run: 7z x ./test/*.zip -obase_folder -aoa
        
  mac_validation_job:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract Files
        run: 7z x ./test/*.zip -obase_folder -aoa

          

