name: ToggleADFTriggers

on:
  workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ADF_CREDENTIAL }}          
          enable-AzPSSession: true 
      - name: Start ADF Triggers
        env:
         ResourceGroupName: "Learn-ADF-RG"
         DataFactoryName: "learn-adf-bk"
        shell: pwsh
        run: |-
            Set-PSRepository PSGallery -InstallationPolicy Trusted
            Install-Module -Name Az.DataFactory -AllowClobber
            $triggers = Get-AzDataFactoryV2Trigger -ResourceGroupName $env:ResourceGroupName -DataFactoryName $env:DataFactoryName       
            foreach($trigger in $triggers){
              Write-Host "Starting Trigger" $trigger
               Start-AzDataFactoryV2Trigger -ResourceGroupName $env:ResourceGroupName -DataFactoryName $env:DataFactoryName -Name $trigger -Force
            }


            
              
              

