name: ToggleADFTriggers

on:
  workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ADF_CREDENTIAL }}
          enable-AzPSSession: true
      - name: Run Azure CLI 
        run: |
          az config set extension.use_dynamic_install=yes_without_prompt
          $triggers = az datafactory trigger list --factory-name "learn-adf-bk" --resource-group "Learn-ADF-RG"
          foreach($trigger in $triggers){
                az datafactory trigger stop --factory-name "learn-adf-bk" --resource-group "Learn-ADF-RG" --name $trigger --only-show-errors
            }
            

            
              
              

