name: ToggleADFTriggers

on:
  workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ADF_CREDENTIAL }}
      - name: Azure CLI Action
        uses: Azure/cli@1.0.4
        with:
          # Specify the script here
          inlineScript: |
            $triggers =	az datafactory trigger list --factory-name "learn-adf-bk" --resource-group "Learn-ADF-RG"  
            Write-Host $triggers

            
              
              

