name: ToggleADFTriggers

on:
  workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ADF_CREDENTIAL }}
      - name: Start ADF Triggers
        env:
         ResourceGroupName: "Learn-ADF-RG"
         DataFactoryName: "learn-adf-bk"
        shell: pwsh
        run: |-
            $triggers = Get-AzDataFactoryV2Trigger -ResourceGroupName $env:ResourceGroupName -DataFactoryName $env:DataFactoryName       
            foreach($trigger in $triggers){
               Start-AzDataFactoryV2Trigger -ResourceGroupName $env:ResourceGroupName -DataFactoryName $env:DataFactoryName -Name $trigger -Force | Out-Null
            }


            
              
              

