name: ToggleADFTriggers

on:
  workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ADF_CREDENTIAL }}          
          enable-AzPSSession: true 
      - name: Toggle ADF Trigger
        env:
          RESOURCE_GROUP_NAME: Learn-ADF-RG
          DATA_FACTORY_NAME: learn-adf-bk
        shell: pwsh
        run: |-
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module -Name Az.DataFactory -AllowClobber
          $triggers = Get-AzDataFactoryV2Trigger -ResourceGroupName $env:RESOURCE_GROUP_NAME -DataFactoryName $env:DATA_FACTORY_NAME
          foreach($trigger in $triggers){
            Write-Host "Start Trigger" $trigger.Name
            Start-AzDataFactoryV2Trigger -ResourceGroupName $env:RESOURCE_GROUP_NAME -DataFactoryName $env:DATA_FACTORY_NAME -Name $trigger.Name -Force
          }

            
              
              

