name: toolfinder

on:
  workflow_dispatch:
  
jobs:

  windowsjob:
    runs-on: windows_latest
    steps:
    - name: "Locate VS Test Executable"
      shell: pwsh
      run: |-
        which vstest.console.exe

 
