name: VS Test

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
    
    # use release mode for build
    env:
      config: 'Release'
      HOME: /home/runner
      NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:    
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build Sox_Audito_ACL_Poc/Sox_Audito_ACL_Poc.sln 
    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1
    - name: VSTest
      run: vstest.console.exe /Platform:x64 ACL_PoC.UnitTests/ACL_PoC.UnitTests.dll
