name: VSTest

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 3.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 5.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Sox_Audito_ACL_Poc/Sox_Audito_ACL_Poc.sln
    - name: Build
      run: dotnet build Sox_Audito_ACL_Poc/Sox_Audito_ACL_Poc.sln --no-restore
    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1
    - name: Install Dependencies for VSTest
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module VstsTaskSdk -AllowClobber
    - name: Executing VSTest
      shell: pwsh
      run: |
       Import-Module -Name VstsTaskSdk
       Write-Host "Finding files for VSTest for execute.."
       $DefaultRoot =  ${{ github.workspace }}
       $ResultsPath =  ${{ github.workspace }}\test-results"
       $Pattern = @("**\\*tests*.dll","!**\\*TestAdapter.dll","!**\\obj\\**")
       $files = Find-VstsMatch -DefaultRoot $DefaultRoot -Pattern $Pattern -Verbose
       Write-Host "Files found:" $files 
       $exe = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe"
       #$args ="/Platform:x64 /ResultsDirectory:""$Resultspath"" /Logger:trx"
       Write-Host $args # consider taking it off after testing
       & $exe $files /Platform:x64 /ResultsDirectory:$Resultspath /Logger:trx    
