name: VSTest

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 3.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 5.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Sox_Audito_ACL_Poc/Sox_Audito_ACL_Poc.sln
    - name: Build
      run: dotnet build Sox_Audito_ACL_Poc/Sox_Audito_ACL_Poc.sln --no-restore
    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1
    - name: Install Dependencies for VSTest
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module VstsTaskSdk -AllowClobber
    - name: Executing VSTest
      env:
        DEFAULT_ROOT: ${{github.workspace}}
      shell: pwsh
      run: |
       Import-Module -Name VstsTaskSdk
       Write-Host "Finding files for VSTest for execute.."
       $DefaultRoot =  $env:DEFAULT_ROOT
       $ResultsPath =  $env:DEFAULT_ROOT\test-results
       $Pattern = @("**\\*tests*.dll","!**\\*TestAdapter.dll","!**\\obj\\**")
       $files = Find-VstsMatch -DefaultRoot $DefaultRoot -Pattern $Pattern -Verbose
       Write-Host "Files found:" $files 
       $exe = "vstest.console.exe"       
       & $exe $files /Platform:x64 /ResultsDirectory:$Resultspath /Logger:trx    
