name: VSTest

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 3.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 5.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Sox_Audito_ACL_Poc/Sox_Audito_ACL_Poc.csproj
    - name: Build
      run: dotnet build Sox_Audito_ACL_Poc/Sox_Audito_ACL_Poc.csproj --no-restore
    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1
    - name: VSTest
      run: vstest.console.exe /Platform:x64 ACL_PoC.UnitTests/ACL_PoC.UnitTests.dll
